trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - "Kubernetes/Base/Windows/*"
    exclude:
      - "*"

pr: none

pool:
  vmImage: "win1803"

variables:
  IMAGE_NAME: "apprenticeshipsdevops/azure-pipelines-base-agent-win"

steps:
  - script: docker pull $(IMAGE_NAME):latest || true
    displayName: "Pull latest docker image to cache"

  - task: Docker@2
    displayName: Build image
    inputs:
      command: build
      repository: $(IMAGE_NAME)
      Dockerfile: "Kubernetes/Base/Windows/Dockerfile"
      arguments: "--cache-from $(IMAGE_NAME):latest -t $(IMAGE_NAME):$(Build.BuildNumber) -t $(IMAGE_NAME):latest"

  - task: Docker@2
    displayName: Docker Hub Login
    inputs:
      command: login
      containerRegistry: "Apprenticeships DevOps Docker Hub"

  - task: Docker@2
    displayName: Push tagged image
    inputs:
      command: push
      repository: $(IMAGE_NAME)
      tags: $(Build.BuildNumber)

  - task: Docker@2
    displayName: Push tagged image (latest) if master
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      command: push
      repository: $(IMAGE_NAME)
      tags: master
