trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - "Linux/Base_Ubuntu20/*"
    exclude:
      - "*"

schedules:
- cron: "0 6 * * Tue"
  displayName: Weekly Tuesday morning build
  branches:
    include:
    - master
  always: true

pr: none

pool:
  vmImage: "Ubuntu-16.04"

variables:
  IMAGE_NAME: "apprenticeshipsdevops/azure-pipelines-base-agent"

steps:
  - script: echo "##vso[task.setvariable variable=IMAGE_NAME_WITH_TAG;]$IMAGE_NAME:$(Build.BuildNumber)"
    displayName: "Set image name with tag"

  - script: docker pull $(IMAGE_NAME):latest || true
    condition: and(succeeded(), ne(variables['Build.Reason'], 'Schedule'))
    displayName: "Pull latest docker image to cache"

  - task: Docker@1
    displayName: Build image with cache
    condition: and(succeeded(), ne(variables['Build.Reason'], 'Schedule'))
    inputs:
      command: Build an image
      imageName: $(IMAGE_NAME)
      dockerFile: Linux/Base_Ubuntu20/Dockerfile
      addDefaultLabels: false
      arguments: "--cache-from $(IMAGE_NAME):latest -t $(IMAGE_NAME_WITH_TAG) -t $(IMAGE_NAME):latest"

  - task: Docker@1
    displayName: Build image without cache
    condition: and(succeeded(), eq(variables['Build.Reason'], 'Schedule'))
    inputs:
      command: Build an image
      imageName: $(IMAGE_NAME)
      dockerFile: Linux/Base_Ubuntu20/Dockerfile
      addDefaultLabels: false
      arguments: "-t $(IMAGE_NAME_WITH_TAG) -t $(IMAGE_NAME):latest"

  - task: Docker@1
    displayName: Docker Hub login
    inputs:
      command: "login"
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: Apprenticeships DevOps Docker Hub

  - task: Docker@1
    displayName: Push tagged image
    inputs:
      command: Push an image
      imageName: $(IMAGE_NAME_WITH_TAG)

  - task: Docker@1
    displayName: Push tagged image (latest) if master
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      command: Push an image
      imageName: $(IMAGE_NAME):latest
